version: '3.8'

services:
  # Serviço do Frontend (Angular)
  frontend-app:
    build: ./compliance-web
    container_name: frontend-app
    ports:
      - "4200:4200" # Acessa via localhost:4200, container expõe na 4200
    volumes:
      - ./compliance-web:/app # Sincroniza seus arquivos locais com os do container
      - /app/node_modules   
    networks:
      - app-network
 

# Volumes para persistência de dados
volumes:
  postgres_data:

# Rede para comunicação entre os containers
networks:
  app-network:
    driver: bridge